apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: db
  name: db
  namespace: {{ .Values.env.CLUSTER_PROJECT_NAME }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
   - port: 5432
  selector:
    service: db