apiVersion: v1
data:
  password: {{ .Values.env.POSTGRES_PASSWORD | toString | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    service: postgresql-password
  name: postgresql-password
  namespace: leadquelle
type: Opaque
