apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.env.CLUSTER_PROJECT_NAME }}-letsencrypt
  namespace: {{ .Values.env.CLUSTER_PROJECT_NAME }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@{{ .Values.env.ERP_DOMAIN }}
    privateKeySecretRef:
      name: {{ .Values.env.CLUSTER_PROJECT_NAME }}-letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx