apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: data
  name: web-data-persistent-volume
  namespace: {{ .Values.env.CLUSTER_PROJECT_NAME }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 16G
  hostPath:
    path: /opt/data/web-data
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  claimRef:
    namespace: {{ .Values.env.CLUSTER_PROJECT_NAME }}
    name: web-data
  volumeMode: Filesystem
---