apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: web-data
  name: web-data
  namespace: {{ .Values.env.CLUSTER_PROJECT_NAME }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16G
  storageClassName: local-path
status: {}
