apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: leadquelle
spec:
  type: NodePort
  ports:
  - name: web
    port: 8069
    targetPort: 8069
  - name: gevent
    port: 8072
    targetPort: 8072
  selector:
    service: web