apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: leadquelle-letsencrypt
  labels:
    service: web
  name: web
  namespace: leadquelle
spec:
  ingressClassName: nginx
#  tls:
#  - hosts:
#    - {{ .Values.env.ERP_DOMAIN }}
#    secretName: tst1-erp-fonfonllc-letsencrypt # TODO: параметризировать для PROD
  rules:
    - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              name: web
      - pathType: Prefix
        path: "/longpolling/poll"
        backend:
          service:
            name: web
            port:
              name: gevent
      - pathType: Prefix
        path: "/websocket"
        backend:
          service:
            name: web
            port:
              name: gevent
#  - host: {{ .Values.env.ERP_DOMAIN }}
#    http:
#      paths:
#      - pathType: Prefix
#        path: "/"
#        backend:
#          service:
#            name: web
#            port:
#              name: web
#      - pathType: Prefix
#        path: "/longpolling/poll"
#        backend:
#          service:
#            name: web
#            port:
#              name: gevent
#      - pathType: Prefix
#        path: "/websocket"
#        backend:
#          service:
#            name: web
#            port:
#              name: gevent