apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
  namespace: leadquelle
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
        - env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-password
                  key: password
            - name: USER
              value: odoo_user
          image: {{ .Values.env.WEB_DOCKER_IMAGE }}
          name: web
          ports:
            - containerPort: 8069
            - containerPort: 8072
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: web-data
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry-{{ .Values.env.CI_PROJECT_PATH_SLUG }}
      volumes:
        - name: web-data
          persistentVolumeClaim:
            claimName: web-data
status: {}
