apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: {{ .Values.env.CLUSTER_PROJECT_NAME }}-letsencrypt
  labels:
    service: web
  name: web
  namespace: {{ .Values.env.CLUSTER_PROJECT_NAME }}
spec:
  defaultBackend:
    service:
      name: web
      port:
        name: web
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.env.ERP_DOMAIN }}
    secretName: {{ .Values.env.CLUSTER_PROJECT_NAME }}-tls-letsencrypt
  rules:
  - host: {{ .Values.env.ERP_DOMAIN }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              name: web
      - pathType: Prefix
        path: "/longpolling/poll"
        backend:
          service:
            name: web
            port:
              name: gevent
      - pathType: Prefix
        path: "/websocket"
        backend:
          service:
            name: web
            port:
              name: gevent