apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: leadquelle-letsencrypt
  namespace: leadquelle
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@fonfonllc.com
    privateKeySecretRef:
      name: leadquelle-letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx