apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.env.CLUSTER_PROJECT_NAME }}-pool
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.env.HOST }}/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.env.CLUSTER_PROJECT_NAME }}
  namespace: metallb-system
spec:
  ipAddressPools:
    - {{ .Values.env.CLUSTER_PROJECT_NAME }}-pool