apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: leadquelle-pool
  namespace: metallb-system
spec:
  addresses:
    - {{ .Values.env.HOST }}/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: leadquelle
  namespace: metallb-system
spec:
  ipAddressPools:
    - leadquelle-pool